modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="vortexmanipulators" #mandatory
version="0.1A" #mandatory
displayName="Vortex Manipulators" #mandatory
#logoFile="vortexmanipulators.png" #optional
credits="The New TARDIS Mod Team" #optional
authors="SpectrumFATM" #optional
description='''
This is an addon mod for the New TARDIS Mod by Spectre0987, Doc Arcane, Suff99, 50ap5ud5 and LotuxPunk.

More Vortex Manipulators adds new functions and variants to the vortex manipulator item from the New TARDIS Mod.

Please note all relevant rights belong to the BBC and associated parties.
'''
[[dependencies.vortexmanipulators]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.vortexmanipulators]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.vortexmanipulators]]
    modId="tardis"
    mandatory=true
    versionRange="[1.5.3,)"
    ordering="AFTER"
    side="BOTH"
